#!/usr/bin/env bash
# a script to fix issues in a ubuntu container
cp -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
echo '9791' | sudo tee /run/nginx.pid
